export default [
    {
       id: 1,
       name: "crash report",
       link: "chrome://crashes",
       description: "allows you to see chrome's crash report",
       color: "#1C73E9",
    },
    {
       id: 2,
       name: "history",
       link:"chrome://history",
       description: "allows you to look at your chrome history",
       color: "#2A9E4C",
    },
    {
       id: 3,
       name: "top sites",
       link: "chrome://thumbnails",
       description: "allows you to see your most visited sites",
       color: "#FDBF07",
    },
    {
       id: 4,
       name: "gpu",
       link: "chrome://gpu",
       description: "view all the gpu stats related to chrome",
       color: "#E23930",
    },
    {
       id: 5,
       name: "new tab",
       link: "chrome://newtab",
       description: "allows you to open a new chrome tab",
       color: "#1C73E9",
    },
    {
       id: 6,
       name: "user actions",
       link: "chrome://user-actions",
       description: "allows you to see your actions while tab is active",
       color: "#2A9E4C",
    },
    {
       id: 7,
       name: "system",
       link: "chrome://system",
       description: "allows you to view your system diagnostic data",
       color: "#FDBF07",
    },
    {
       id: 8,
       name: "apps",
       link: "chrome://apps",
       description: "allows you to view and access all of your chrome applications",
       color: "#E23930",
    },
    {
       id: 9,
       name: "downloads",
       link: "chrome://downloads",
       description: "allows you to view all web downloads made from chrome",
       color: "#1C73E9",
    },
    {
       id: 10,
       name: "extensions",
       link: "chrome://extensions",
       description: "allows you to see what chrome extensions are running",
       color: "#2A9E4C",
    },
    {
       id: 11,
       name: "version",
       link: "chrome://version",
       description: "shows your chrome stats",
       color: "#FDBF07",
    },
    {
       id: 12,
       name: "plugins",
       link: "chrome://plugins",
       description: "allows you to see what chrome plugins are running",
       color: "#E23930",
    },
    {
       id: 13,
       name: "settings",
       link: "chrome://settings",
       description: "allows you to access the chrome settings menu",
       color: "#1C73E9",
    },
    {
       id: 14,
       name: "bookmarks",
       link: "chrome://bookmarks",
       description: "allows you to open, view, and edit chrome bookmarks",
       color: "#2A9E4C",
    },
    {
       id: 15,
       name: "flags",
       link: "chrome://flags",
       description: "allows you to try chrome's experimental features",
       color: "#FDBF07",
    },
    {
       id: 16,
       name: "restart",
       link: "chrome://restart",
       description: "allows you to restart the chrome application",
       color: "#E23930",
    },
 ];